Revision: 37f12e376e328f8e8e677ce4e11c5d72589553ac
Patch-set: 3
File: test/587-inline-class-error/src/Main.java

28:4-28:49
Fri Mar 18 16:22:13 2016 +0000
Author: Roland Levillain <1052644@85c56323-6fa9-3386-8a01-6480fb634889>
UUID: 9cb846d6_d962f382
Bytes: 56
Does this really work?  I didn't know you could do that.

30:6-30:93
Fri Mar 18 16:21:11 2016 +0000
Author: Vladimir Marko <1018108@85c56323-6fa9-3386-8a01-6480fb634889>
UUID: bcb50adc_9da787d5
Bytes: 186
This is `TestCase.topLevel(null)` and the NPE will be thrown on the aget-object. I'd rather see the NPE thrown by the invoke-virtual from `TestCase.topLevel(new VerifyError[] { null })`.

33:6-33:17
Fri Mar 18 16:21:11 2016 +0000
Author: Vladimir Marko <1018108@85c56323-6fa9-3386-8a01-6480fb634889>
UUID: 7cd6320e_43999893
Bytes: 73
And you should check `e.getCause() instanceof NullPointerException` here.

