Revision: 37f12e376e328f8e8e677ce4e11c5d72589553ac
Patch-set: 3
File: test/587-inline-class-error/src/Main.java

28:4-28:49
Fri Mar 18 16:22:13 2016 +0000
Author: Roland Levillain <1052644@85c56323-6fa9-3386-8a01-6480fb634889>
UUID: 9cb846d6_d962f382
Bytes: 56
Does this really work?  I didn't know you could do that.

30:6-30:93
Fri Mar 18 16:21:11 2016 +0000
Author: Vladimir Marko <1018108@85c56323-6fa9-3386-8a01-6480fb634889>
UUID: bcb50adc_9da787d5
Bytes: 186
This is `TestCase.topLevel(null)` and the NPE will be thrown on the aget-object. I'd rather see the NPE thrown by the invoke-virtual from `TestCase.topLevel(new VerifyError[] { null })`.

30:6-30:93
Fri Mar 18 16:35:30 2016 +0000
Author: Nicolas Geoffray <1038443@85c56323-6fa9-3386-8a01-6480fb634889>
Parent: bcb50adc_9da787d5
UUID: bcb50adc_5df08fb4
Bytes: 131
I don't think you can. VerifyError is erroneous, and AFAICS reflection does not allow you to create an array of an erroneous class.

30:6-30:93
Fri Mar 18 16:48:21 2016 +0000
Author: Vladimir Marko <1018108@85c56323-6fa9-3386-8a01-6480fb634889>
Parent: bcb50adc_5df08fb4
UUID: 9ccf6672_81b0fa24
Bytes: 119
And can the code instantiate such array using the `new-array` opcode? (You'd have to write a helper function in smali.)

30:6-30:93
Mon Mar 21 11:25:40 2016 +0000
Author: Nicolas Geoffray <1038443@85c56323-6fa9-3386-8a01-6480fb634889>
Parent: 9ccf6672_81b0fa24
UUID: dce47ef9_fbe24f19
Bytes: 35
Good point, I now do this in smali.

33:6-33:17
Fri Mar 18 16:21:11 2016 +0000
Author: Vladimir Marko <1018108@85c56323-6fa9-3386-8a01-6480fb634889>
UUID: 7cd6320e_43999893
Bytes: 73
And you should check `e.getCause() instanceof NullPointerException` here.

33:6-33:17
Fri Mar 18 16:35:30 2016 +0000
Author: Nicolas Geoffray <1038443@85c56323-6fa9-3386-8a01-6480fb634889>
Parent: 7cd6320e_43999893
UUID: 9ccf6672_e1e54624
Bytes: 4
Done

