Revision: b567aaf5b2548990e9d28e460cff4169121bec7e
Patch-set: 2
File: runtime/verifier/method_verifier.cc

4001:13-4001:40
Wed Mar 16 21:23:00 2016 +0000
Author: Andreas Gampe <1041833@85c56323-6fa9-3386-8a01-6480fb634889>
UUID: 9cd5a6d1_17e63cd4
Bytes: 169
Can you verify this against the RI? I'm curious whether this is a hard runtime failure, or should be thrown at the point of the invoke (so, e.g., VERIFY_ERROR_NO_CLASS).

4001:13-4001:40
Wed Mar 16 21:41:05 2016 +0000
Author: Alex Light <1047769@85c56323-6fa9-3386-8a01-6480fb634889>
Parent: 9cd5a6d1_17e63cd4
UUID: 9cd5a6d1_b7a89051
Bytes: 86
Good catch. It should be VERIFY_ERROR_NO_CLASS and throw at location of invoke.

Done.

