Revision: eae2fb27c91aa7972dffcb32d5e405567badd6aa
Patch-set: 1
File: runtime/verifier/method_verifier.cc

3528:0-3528:29
Tue Jan 14 23:42:33 2014 +0000
Author: Ian Rogers <1010118@85c56323-6fa9-3386-8a01-6480fb634889>
UUID: ed294520_3d74f3e2
Bytes: 54
Weird we didn't need the clear before, a missing test?

3528
Wed Jan 15 00:01:23 2014 +0000
Author: Mathieu Chartier <1015378@85c56323-6fa9-3386-8a01-6480fb634889>
Parent: ed294520_3d74f3e2
UUID: 4deed135_5f9e2b78
Bytes: 226
Before we always passed in false, this meant that exceptions could never get thrown. I started getting some errors caused by exceptions after changing it to can_load_classes_ so I added the ClearException. I assume this is OK?

3594:26-3594:29
Tue Jan 14 23:42:33 2014 +0000
Author: Ian Rogers <1010118@85c56323-6fa9-3386-8a01-6480fb634889>
UUID: ed294520_dd513f50
Bytes: 8
and here

3594
Wed Jan 15 00:01:23 2014 +0000
Author: Mathieu Chartier <1015378@85c56323-6fa9-3386-8a01-6480fb634889>
Parent: ed294520_dd513f50
UUID: 4deed135_bf13f73e
Bytes: 5
Same.

3692:0-3692:27
Tue Jan 14 23:42:33 2014 +0000
Author: Ian Rogers <1010118@85c56323-6fa9-3386-8a01-6480fb634889>
UUID: cd26414f_1c3fb939
Bytes: 8
and here

3692
Wed Jan 15 00:01:23 2014 +0000
Author: Mathieu Chartier <1015378@85c56323-6fa9-3386-8a01-6480fb634889>
Parent: cd26414f_1c3fb939
UUID: 0df0590e_9d32830d
Bytes: 5
Same.

